package pacote;

import ferramentas.CaixaDeDialogo;
import ferramentas.Formatacao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;

/**
 *
 * @author Usuario
 */
public class InterfaceBanco extends javax.swing.JFrame {

    public Conta conta1;
    public Conta conta2;
    
    public InterfaceBanco() {
        initComponents();
        
    }

    private void atualizarInformacoesTela(){
        
        ContaController controller = new ContaController();
        float saldoConta1 = controller.buscarSaldo(conta1.getId());
        float saldoConta2 = controller.buscarSaldo(conta2.getId());
        
        conta1.setSaldo(saldoConta1);
        conta2.setSaldo(saldoConta2);
        
        lblConta1.setText(conta1.getNome());
        lblSaldoConta1.setText(String.valueOf(conta1.getSaldo()));
        lblChequeEspecialConta1.setText(String.valueOf(conta1.getCheque_especial()));
        lblConta2.setText(conta2.getNome());
        lblSaldoConta2.setText(String.valueOf(conta2.getSaldo()));
        lblChequeEspecialConta2.setText(String.valueOf(conta2.getCheque_especial()));
        
        controller.preencher(jtbTabela);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConta1 = new javax.swing.JLabel();
        lblConta2 = new javax.swing.JLabel();
        btnTransferirConta1 = new javax.swing.JButton();
        btnTransferir2 = new javax.swing.JButton();
        txtValor2 = new javax.swing.JTextField();
        txtConta1 = new javax.swing.JTextField();
        lblSaldoConta1 = new javax.swing.JLabel();
        lblSaldoConta2 = new javax.swing.JLabel();
        btnSacarConta1 = new javax.swing.JButton();
        btnDepositarConta1 = new javax.swing.JButton();
        btnDepositar2 = new javax.swing.JButton();
        btnSacar2 = new javax.swing.JButton();
        lblChequeEspecialConta1 = new javax.swing.JLabel();
        lblChequeEspecialConta2 = new javax.swing.JLabel();
        txtValor3 = new javax.swing.JTextField();
        lblData1 = new javax.swing.JLabel();
        txtData1 = new javax.swing.JTextField();
        btnData2 = new javax.swing.JButton();
        btnData1 = new javax.swing.JButton();
        btnData3 = new javax.swing.JButton();
        txtNumeros = new javax.swing.JTextField();
        lblNumeros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConta1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConta1.setForeground(new java.awt.Color(102, 102, 102));
        lblConta1.setText("CONTA 1");
        getContentPane().add(lblConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 6, -1, -1));

        lblConta2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConta2.setForeground(new java.awt.Color(102, 102, 102));
        lblConta2.setText("CONTA 2");
        getContentPane().add(lblConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 6, -1, -1));

        btnTransferirConta1.setText("Transferir");
        btnTransferirConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirConta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransferirConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 99, -1, -1));

        btnTransferir2.setText("Transferir");
        btnTransferir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferir2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransferir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 99, -1, -1));
        getContentPane().add(txtValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 71, 79, -1));
        getContentPane().add(txtConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 71, 79, -1));

        lblSaldoConta1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSaldoConta1.setForeground(new java.awt.Color(102, 102, 102));
        lblSaldoConta1.setText("SALDO");
        getContentPane().add(lblSaldoConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 28, -1, -1));

        lblSaldoConta2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSaldoConta2.setForeground(new java.awt.Color(102, 102, 102));
        lblSaldoConta2.setText("SALDO");
        getContentPane().add(lblSaldoConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 28, -1, -1));

        btnSacarConta1.setText("Sacar");
        btnSacarConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarConta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSacarConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 127, 79, -1));

        btnDepositarConta1.setText("Depositar");
        btnDepositarConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarConta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDepositarConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 155, -1, -1));

        btnDepositar2.setText("Depositar");
        btnDepositar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDepositar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 155, -1, -1));

        btnSacar2.setText("Sacar");
        btnSacar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSacar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 127, 80, -1));

        lblChequeEspecialConta1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblChequeEspecialConta1.setForeground(new java.awt.Color(102, 102, 102));
        lblChequeEspecialConta1.setText("CHEQUE");
        getContentPane().add(lblChequeEspecialConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblChequeEspecialConta2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblChequeEspecialConta2.setForeground(new java.awt.Color(102, 102, 102));
        lblChequeEspecialConta2.setText("CHEQUE");
        getContentPane().add(lblChequeEspecialConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 49, -1, -1));
        getContentPane().add(txtValor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 71, 79, -1));

        lblData1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblData1.setForeground(new java.awt.Color(102, 102, 102));
        lblData1.setText("DATA");
        getContentPane().add(lblData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 80, -1));
        getContentPane().add(txtData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 80, -1));

        btnData2.setText("CONVERTE PARA DMA");
        btnData2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnData2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnData2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 170, -1));

        btnData1.setText("CONVERTE PARA AMD");
        btnData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnData1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 170, -1));

        btnData3.setText("APENAS NUMEROS");
        btnData3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnData3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnData3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 170, -1));
        getContentPane().add(txtNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 80, -1));

        lblNumeros.setForeground(new java.awt.Color(102, 102, 102));
        lblNumeros.setText("jLabel1");
        getContentPane().add(lblNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 80, -1));

        jtbTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbTabela);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 317, 380, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositarConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarConta1ActionPerformed
        try{
            float valor = Float.parseFloat(txtConta1.getText());
            
            ContaController controller = new ContaController();
            boolean retorno = controller.debito(conta1, valor);
            if(retorno){
                atualizarInformacoesTela();
                CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
                System.out.println("Operação de débito " + valor);
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao realizar operação", 'e');
            }
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_btnDepositarConta1ActionPerformed

    private void btnSacarConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarConta1ActionPerformed
        try{
            float valor = Float.parseFloat(txtConta1.getText());
            
            ContaController controller = new ContaController();
            boolean retorno = controller.credito(conta1, valor);
            if(retorno){
                atualizarInformacoesTela();
                CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
                System.out.println("Operação de crédito " + valor);
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao realizar operação", 'e');
            }
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
        
    }//GEN-LAST:event_btnSacarConta1ActionPerformed

    private void btnDepositar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositar2ActionPerformed
        try{
            float valor = Float.parseFloat(txtValor2.getText());
            
            ContaController controller = new ContaController();
            boolean retorno = controller.debito(conta2, valor);
            if(retorno){
                atualizarInformacoesTela();
                CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
                System.out.println("Operação de débito " + valor);
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao realizar operação", 'e');
            }
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_btnDepositar2ActionPerformed

    private void btnSacar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacar2ActionPerformed
         try{
            float valor = Float.parseFloat(txtValor2.getText());
            
            ContaController controller = new ContaController();
            boolean retorno = controller.credito(conta2, valor);
            if(retorno){
                atualizarInformacoesTela();
                CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
                System.out.println("Operação de crédito " + valor);
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao realizar operação", 'e');
            }
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_btnSacar2ActionPerformed

    private void btnTransferirConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirConta1ActionPerformed
        try{
            
            float valor = Float.parseFloat(txtConta1.getText());
            //tenta realizar um saque da conta 1
            //boolean resultado = conta1.credito(valor);
            ContaController controller = new ContaController();
            boolean resultado = controller.credito(conta1, valor);
            if(resultado){
                //se der certo, vai depositar esse valor na conta 2
                //conta2.debito(valor);
                resultado = controller.debito(conta2, valor);
                if(resultado){
                    atualizarInformacoesTela();
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
                }else{
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Erro na operação", 'a');
                 }
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Saldo insuficiente", 'a');
            }
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_btnTransferirConta1ActionPerformed

    private void btnTransferir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferir2ActionPerformed
//        try{
//            
//            float valor = Float.parseFloat(txtValor2.getText());
//            //tenta realizar um saque da conta 2
//            boolean resultado = conta2.credito(valor);
//            if(resultado){
//                //se der certo, vai depositar esse valor na conta 1
//                conta1.debito(valor);
//                atualizarInformacoesTela();
//                CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
//            }else{
//                CaixaDeDialogo.obterinstancia().exibirMensagem("Saldo insuficiente", 'a');
//            }
//            
//        }catch(Exception ex){
//            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
//        }
    }//GEN-LAST:event_btnTransferir2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ContaController controller = new ContaController();
        //conta1 = controller.buscar(1);
        conta2 = controller.buscar(2);
        
        atualizarInformacoesTela();
    }//GEN-LAST:event_formWindowOpened

    private void btnData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnData1ActionPerformed
        try{
            
            String retorno = "";
            String data_amd = txtData1.getText();
            retorno = Formatacao.ajustaDataDMA(data_amd);
            
            lblData1.setText(retorno);
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_btnData1ActionPerformed

    private void btnData2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnData2ActionPerformed
        try{
            
            String retorno = "";
            String data_dma = txtData1.getText();
            retorno = Formatacao.ajustaDataAMD(data_dma);
            
            lblData1.setText(retorno);
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_btnData2ActionPerformed

    private void btnData3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnData3ActionPerformed
       try{
            
            lblNumeros.setText(Formatacao.removerFormatacao(txtNumeros.getText()));
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_btnData3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnData1;
    private javax.swing.JButton btnData2;
    private javax.swing.JButton btnData3;
    private javax.swing.JButton btnDepositar2;
    private javax.swing.JButton btnDepositarConta1;
    private javax.swing.JButton btnSacar2;
    private javax.swing.JButton btnSacarConta1;
    private javax.swing.JButton btnTransferir2;
    private javax.swing.JButton btnTransferirConta1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbTabela;
    private javax.swing.JLabel lblChequeEspecialConta1;
    private javax.swing.JLabel lblChequeEspecialConta2;
    private javax.swing.JLabel lblConta1;
    private javax.swing.JLabel lblConta2;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblNumeros;
    private javax.swing.JLabel lblSaldoConta1;
    private javax.swing.JLabel lblSaldoConta2;
    private javax.swing.JTextField txtConta1;
    private javax.swing.JTextField txtData1;
    private javax.swing.JTextField txtNumeros;
    private javax.swing.JTextField txtValor2;
    private javax.swing.JTextField txtValor3;
    // End of variables declaration//GEN-END:variables
}
